UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_gian_carlo.jpg' WHERE name_ro = 'Gian Carlo';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_capriciosa.jpg' WHERE name_ro = 'Capriciosa';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_burger_barbecue.jpg' WHERE name_ro = 'Meniu BBQ Burger';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_shaorma.jpg' WHERE name_ro = 'Shaorma la Farfurie';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/coca-cola-500ml.png' WHERE name_ro = 'Coca-Cola 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/coca-cola-can-330ml.png' WHERE name_ro = 'Coca-Cola 0.33L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/coca-cola-zero-330ml.png' WHERE name_ro = 'Coca-Cola Zero 0.33L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/fanta-orange-500ml.png' WHERE name_ro = 'Fanta Portocale 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/fanta-madness-330ml.png' WHERE name_ro = 'Fanta Madness 0.33L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/fanta-pear-500ml.png' WHERE name_ro = 'Fanta Pear 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/sprite-500ml.png' WHERE name_ro = 'Sprite 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/schweppes-mandarin-500ml.png' WHERE name_ro = 'Schweppes Mandarin 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/cappy-portocale-330ml.png' WHERE name_ro = 'Cappy Portocale 0.33L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/cappy-lemonade-400ml.png' WHERE name_ro = 'Cappy Lemonade 0.4L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/fuze-tea-piersica-500ml.png' WHERE name_ro = 'Fuze Tea Piersică 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/fuze-tea-berries-500ml.png' WHERE name_ro = 'Fuze Tea Forest Fruit 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/monster-500ml.png' WHERE name_ro = 'Monster Energy 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/apa-dorna-500ml.png' WHERE name_ro = 'Apă Dorna 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/heineken.jpg' WHERE name_ro = 'Heineken 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_burger_spicy.jpg' WHERE name_ro = 'Meniu Spicy Burger';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_burger_classic.jpg' WHERE name_ro = 'Meniu Classic Burger';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_burger_crispy.jpg' WHERE name_ro = 'Meniu Crispy Burger';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_burgeri.jpeg' WHERE name_ro = 'Burger Rolls';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-items/pizza_vegetariana.jpg' WHERE name_ro = 'Pizza Vegetariană';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_ciuperci.jpg' WHERE name_ro = 'Meniu ciuperci la grătar';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_anastasia.jpg' WHERE name_ro = 'Pizza Anastasia';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_strumfi.jpg' WHERE name_ro = 'Pizza Ștrumf';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_chicken.jpg' WHERE name_ro = 'Chicken';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_quattro_stagioni.jpg' WHERE name_ro = 'Quattro Stagioni';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_diavolo.jpg' WHERE name_ro = 'Diavolo';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza.jpeg' WHERE name_ro = 'Napoli';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_claudiu.jpg' WHERE name_ro = 'Claudiu';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_vegetariana.jpg' WHERE name_ro = 'Vegetariană';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_taraneasca.jpg' WHERE name_ro = 'Țărănească';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_quattro_carni.jpg' WHERE name_ro = 'Quattro Carni';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_bacon.jpg' WHERE name_ro = 'Bacon';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza.jpeg' WHERE name_ro = 'Calzone Speciale';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_tonno.jpg' WHERE name_ro = 'Tonno';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_prosciutto_e_funghi.jpg' WHERE name_ro = 'Prosciutto e Funghi';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_carbonara.jpg' WHERE name_ro = 'Carbonara';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_daco_romana.jpg' WHERE name_ro = 'Daco-Romană';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_anastasia.jpg' WHERE name_ro = 'Pizza pt copii – Anastasia';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza_strumfi.jpg' WHERE name_ro = 'Pizza pt copii – Ștrumf';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza.jpeg' WHERE name_ro = 'Pizza pt copii – Prichindel';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/pizza.jpeg' WHERE name_ro = 'Pizza Creată';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_piept_de_pui.jpg' WHERE name_ro = 'Piept de pui la grătar';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_snitel.jpg' WHERE name_ro = 'Meniu Șnițel de pui';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_crispy.jpg' WHERE name_ro = 'Meniu Crispy la farfurie';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_crispy.jpg' WHERE name_ro = 'Chicken Box';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_crispy.jpg' WHERE name_ro = 'Crispy Box';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_nuggets.jpg' WHERE name_ro = 'Nuggets Box';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_mozzarella_sticks.jpg' WHERE name_ro = 'Mozzarella Sticks';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_aripioare_picante.jpg' WHERE name_ro = 'Meniu Aripioare Picante';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_shaorma.jpg' WHERE name_ro = 'Crispy Chicken Rolls';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_shaorma.jpg' WHERE name_ro = 'Chicken Rolls';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/meniu_combo_1.jpeg' WHERE name_ro = 'Combo Box 1';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/salata_romaneasca.jpg' WHERE name_ro = 'Salată Românească';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/salata_italiana.jpg' WHERE name_ro = 'Salată Italiană';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/salata_puisor.jpg' WHERE name_ro = 'Salată Puișor';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/salata_bulgareasca.jpg' WHERE name_ro = 'Salată Bulgărească';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/salata_cu_piept_de_pui.jpg' WHERE name_ro = 'Salată cu piept de pui';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/salata_crispy.jpg' WHERE name_ro = 'Salată Crispy';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/salata_cu_ton.jpg' WHERE name_ro = 'Salată de ton';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/salata_fresh.jpg' WHERE name_ro = 'Salată Fresh';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/sos_rosii.jpg' WHERE name_ro = 'Sos de roșii';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/sos_maioneza.jpg' WHERE name_ro = 'Sos de maioneză';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/sos_cocktail.jpeg' WHERE name_ro = 'Sos cocktail';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/sos_cheddar.jpg' WHERE name_ro = 'Sos cheddar';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/Ciuc-Premium-768x1024.jpg' WHERE name_ro = 'Ciuc Premium 0.33L/0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/Amstel-768x1024.jpg' WHERE name_ro = 'Amstel 0.33L/0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/Birra-Moretti_330_2-768x1024.jpg' WHERE name_ro = 'Birra Moretti 0.33L/0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/Golden-Brau-1-768x1024.jpg' WHERE name_ro = 'Golden Brau 0.5L';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/WhatsApp-Image-2026-04-05-at-13.07.22-1-e1775391366759-839x1024.jpeg' WHERE name_ro = 'Margherita';
UPDATE menu_items SET image_url = 'https://ipakwhqygsltsjixmgec.supabase.co/storage/v1/object/public/menu-images/heineken.jpg' WHERE name_ro = 'Ciuc Premium';